# Creating single csv export that has a 1-1 many relationship with allocation and site.

In [1]:
#Needed Libaraies
import os
import numpy as np
import pandas as pd

In [2]:
#Setting work directory, reading inputs, creating dataframe
workingDir = "C:/Users/rjame/Documents/WSWC Documents/Portal Creation Research"
os.chdir(workingDir)
fileInput = "dontopen_WaDEQAQuery_All.csv"
#fileInput = "dontopen_WaDEQAQuery_CO.csv"
#fileInput = "dontopen_WaDEQAQuery_UT.csv"
#fileInput = "dontopen_WaDEQAQuery_AZ.csv"
#fileInput = "dontopen_WaDEQAQuery_NM.csv"
df = pd.read_csv(fileInput)

C:\Users\rjame\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3063: DtypeWarning: Columns (0) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [3]:
df

,AllocationNativeID,AllocationAmountID,AllocationAmount,AllocationMaximum,IrrigatedAcreage,AllocationPriorityDateID,PrimaryUseCategoryCV,BeneficialUseCV,Date,SiteID,SiteUUID,Longitude,Latitude,WaterSourceID,WaterSourceName,OrganizationID,OrganizationUUID,State
0,00-190,530436,0.000,0.476,0.000,25998,Irrigation,NaN,2003-05-28,1443486.0,UTDWRE_14300,-111.764086,40.129009,395582,Underground Water Well,3,UTDWRE,UT
1,00-276,530437,0.000,69.160,13.832,23216,Irrigation,NaN,2003-09-11,1442882.0,UTDWRE_13758,-111.896981,40.359477,395584,Utah Lake and Jordan River,3,UTDWRE,UT
2,00-276,530437,0.000,69.160,13.832,23216,Irrigation,NaN,2003-09-11,1442883.0,UTDWRE_13759,-111.929898,40.457153,395584,Utah Lake and Jordan River,3,UTDWRE,UT
3,01-1059,530438,0.000,0.250,0.000,25216,Irrigation,Other,1861-01-01,1448482.0,UTDWRE_18799,-109.273909,39.450597,397115,Middle Canyon Reservoir,3,UTDWRE,UT
4,01-1059,530438,0.000,0.250,0.000,25216,Irrigation,Stockwatering,1861-01-01,1448482.0,UTDWRE_18799,-109.273909,39.450597,397115,Middle Canyon Reservoir,3,UTDWRE,UT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1057908,57656.0-0-C-3005293,1713759,0.222,0.000,NaN,18921,Irrigation,NaN,2007-11-09,3776548.0,CO_121368,-107.848170,37.392177,40836,GROUNDWATER: ANIMAS RIVER,1,CODWR,CO
1057909,21523.18388-0-C-3903956,1713760,0.000,0.000,NaN,20362,Irrigation,NaN,1900-05-06,3777047.0,CO_121867,-108.085283,39.472796,42718,PARACHUTE CREEK,1,CODWR,CO
1057910,8157.0-9-C-1200520,1713761,1.690,0.000,NaN,1867,Irrigation,NaN,1872-05-01,3782862.0,CO_127682,-105.275700,38.788897,38576,FOURMILE CREEK,1,CODWR,CO
1057911,20560.0-0-C-100902,1713762,400.000,0.000,NaN,11636,Irrigation,Irrigation,1906-04-17,3785783.0,CO_130603,-104.624246,40.595127,38351,OWL CREEK,1,CODWR,CO
1057912,59017.0-0-C-1900830,1713763,1.000,0.000,NaN,3315,Irrigation,Storage,2011-08-01,3779589.0,CO_124409,-104.792529,37.082782,40430,LORENCITO CANYON,1,CODWR,CO

In [4]:
df.dtypes

AllocationNativeID           object
AllocationAmountID            int64
AllocationAmount            float64
AllocationMaximum           float64
IrrigatedAcreage            float64
AllocationPriorityDateID      int64
PrimaryUseCategoryCV         object
BeneficialUseCV              object
Date                         object
SiteID                      float64
SiteUUID                     object
Longitude                   float64
Latitude                    float64
WaterSourceID                 int64
WaterSourceName              object
OrganizationID                int64
OrganizationUUID             object
State                        object
dtype: object

In [5]:
#removeing bad rows of df because they are null for some odd reason
df = df[(df.WaterSourceName != 'test')]

In [6]:
#changing data type of 'Date' to datatype, then changing format of 'Date' to yyyy-mm-dd
df['Date'] = pd.to_datetime(df['Date'], errors = 'coerce')
df['Date'] = pd.to_datetime(df["Date"].dt.strftime('%m/%d/%Ym'))

In [7]:
WSWCBenUseDict = {
"Irrigation" : "Agricultural",
"Agriculture" : "Agricultural",
"Irrigation Storage" : "Agricultural",
"Agriculture other than irrigation" : "Agricultural",
"Commercial" : "Commercial",
"Commercial From Storage" : "Commercial",
"Commercial Storage" : "Commercial",
"72-12-1 Sanitary in conjunction with a commercial use" : "Commercial",
"Domestic" : "Domestic",
"72-12-1 domestic and livestock watering" : "Domestic",
"72-12-1 domestic one household" : "Domestic",
"72-12-1 multiple domestic households" : "Domestic",
"Mobile home parks" : "Domestic",
"Subdivision" : "Domestic",
"Household Use Only" : "Domestic",
"Domestic From Storage" : "Domestic",
"Domestic Storage" : "Domestic",
"Public utility" : "Domestic",
"Minimum Streamflow" : "Environmental",
"Ground Water Recharge" : "Environmental",
"Ground Water Recharge From Storage" : "Environmental",
"Ground Water Recharge Storage" : "Environmental",
"Lake Level Maintenance" : "Environmental",
"Minimum Stream Flow" : "Environmental",
"Mitigation" : "Environmental",
"72-12-1 Prospecting or development of natural resource" : "Environmental",
"Pollution control well" : "Environmental",
"Pollution Abatement" : "Environmental",
"Fire" : "Fire",
"Fire Protection" : "Fire",
"Fire Protection From Storage" : "Fire",
"Fire Protection Storage" : "Fire",
"Flood Control Storage" : "Flood Control",
"Flood Control" : "Flood Control",
"Industrial" : "Industrial",
"Cemetery" : "Industrial",
"Construction" : "Industrial",
"Dairy operation" : "Industrial",
"Domestic construction" : "Industrial",
"Highway construction" : "Industrial",
"Oil production" : "Industrial",
"Poultry and egg operation" : "Industrial",
"Industrial From Storage" : "Industrial",
"Industrial Storage" : "Industrial",
"Irrigation From Storage" : "Industrial",
"72-12-1 Construction of public works" : "Industrial",
"Petroleum processing plant" : "Industrial",
"Secondary recovery of oil" : "Industrial",
"Stockwater" : "Livestock",
"Stockwater From Storage" : "Livestock",
"Stockwater Storage" : "Livestock",
"72-12-1 livestock watering" : "Livestock",
"Stock" : "Livestock",
"Stockwatering" : "Livestock",
"Mining" : "Mining",
"Mining From Storage" : "Mining",
"Mining Storage" : "Mining",
"Mining or milling or oil" : "Mining",
"Municipal" : "Municipal",
"Municipal From Storage" : "Municipal",
"Municipal Storage" : "Municipal",
"Municipal - city or county supplied water" : "Municipal",
"Geothermal" : "Power",
"Power From Storage" : "Power",
"Power Storage" : "Power",
"Geothermal boreholes" : "Power",
"Power" : "Power",
"Power Generation" : "Power",
"Recharge" : "Recharge",
"Recreation From Storage" : "Recreation",
"Recreation Storage" : "Recreation",
"Recreation" : "Recreation",
"Snow Making" : "Snow Making",
"Storage" : "Storage",
"Fishery" : "Wildlife",
"Fish Habitat" : "Wildlife",
"Fish Habitat Storage" : "Wildlife",
"Fish Propagation" : "Wildlife",
"Fish Propagation From Storage" : "Wildlife",
"Fish Propagation Storage" : "Wildlife",
"Wildlife From Storage" : "Wildlife",
"Wildlife Storage" : "Wildlife",
"Wildlife" : "Wildlife",
"Fish And Wildlife" : "Wildlife",
"Fish and game propogation" : "Wildlife"}


def assignWSWCBU(colrowValue):
    if colrowValue == '' or pd.isnull(colrowValue):
        outList = "Other"
    else:
        String1 = colrowValue  # remove whitespace chars
        try:
            outList = WSWCBenUseDict[String1]
        except:
            outList = "Other"
    return outList

df['WSWCBeneficialUse'] = df.apply(lambda row: assignWSWCBU(row['BeneficialUseCV']), axis=1)

In [8]:
WSWCBenUseColorDict = {
"Agricultural " : "Yellow",
"Commercial " : "DarkGreen",
"Domestic " : "Blue",
"Fire " : "Crimson",
"Industrial " : "BlueViolet",
"Mining " : "Gold",
"Municipal " : "Black",
"Power " : "DarkOrange",
"Recreation " : "Fuchsia",
"Snow Making " : "MintCream",
"StockWatering " : "DarkTurquoise",
"Wildlife " : "PaleGreen",
"Other " : "SlateGray"}


def assignWSWCBUColor(colrowValue):
    if colrowValue == '' or pd.isnull(colrowValue):
        return "SlateGray"
    else:
        String1 = colrowValue  # remove whitespace chars
        try:
            outList = WSWCBenUseColorDict[String1]
        except:
            outList = "SlateGray"
    return outList

df['WBenUseColor'] = df.apply(lambda row: assignWSWCBUColor(row['WSWCBeneficialUse']), axis=1)

In [9]:
#Removing NaN, and missing (999) values from AllocaitonAmount, AllocaitonMaxium, IrrigatedAcerage.
df['AllocationAmount'] = df['AllocationAmount'].fillna(0)
df['AllocationAmount'] = df['AllocationAmount'].replace(999, 0)

df['AllocationMaximum'] = df['AllocationMaximum'].fillna(0)
df['AllocationMaximum'] = df['AllocationMaximum'].replace(999, 0)

df['IrrigatedAcreage'] = df['IrrigatedAcreage'].fillna(0)
df['IrrigatedAcreage'] = df['IrrigatedAcreage'].replace(999, 0)

In [10]:
#Outbound DataFrame
#outdf = pd.DataFrame(index = df.index)
outdf = pd.DataFrame()

outdf['IndexNum'] = df.index
outdf['SiteUUID'] = df['SiteUUID'].astype(str) 
outdf['Lat'] = df['Latitude'].astype(float) 
outdf['Long'] = df['Longitude'].astype(float) 
outdf['AA_ID'] = df['AllocationAmountID'].astype(str)
outdf['SN_ID'] = df['AllocationNativeID'].astype(str) 
outdf['State'] = df['State'].astype(str) 
outdf['AA_CFS'] = df['AllocationAmount'].astype(float) 
outdf['AA_AF'] = df['IrrigatedAcreage'].astype(float) 
outdf['AAM_AF'] = df['AllocationMaximum'].astype(float) 
outdf['PD'] = df['Date']
outdf['WSN'] = df['WaterSourceName'].astype(str) 
outdf['WBenUse'] = df['WSWCBeneficialUse'].astype(str)
outdf['WBenUseColor'] = df['WBenUseColor'].astype(str)

outdf.reset_index()

,index,IndexNum,SiteUUID,Lat,Long,AA_ID,SN_ID,State,AA_CFS,AA_AF,AAM_AF,PD,WSN,WBenUse,WBenUseColor
0,0,0,UTDWRE_14300,40.129009,-111.764086,530436,00-190,UT,0.000,0.000,0.476,2003-05-28,Underground Water Well,Other,SlateGray
1,1,1,UTDWRE_13758,40.359477,-111.896981,530437,00-276,UT,0.000,13.832,69.160,2003-09-11,Utah Lake and Jordan River,Other,SlateGray
2,2,2,UTDWRE_13759,40.457153,-111.929898,530437,00-276,UT,0.000,13.832,69.160,2003-09-11,Utah Lake and Jordan River,Other,SlateGray
3,3,3,UTDWRE_18799,39.450597,-109.273909,530438,01-1059,UT,0.000,0.000,0.250,1861-01-01,Middle Canyon Reservoir,Other,SlateGray
4,4,4,UTDWRE_18799,39.450597,-109.273909,530438,01-1059,UT,0.000,0.000,0.250,1861-01-01,Middle Canyon Reservoir,Livestock,SlateGray
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1057908,1057908,1057908,CO_121368,37.392177,-107.848170,1713759,57656.0-0-C-3005293,CO,0.222,0.000,0.000,2007-11-09,GROUNDWATER: ANIMAS RIVER,Other,SlateGray
1057909,1057909,1057909,CO_121867,39.472796,-108.085283,1713760,21523.18388-0-C-3903956,CO,0.000,0.000,0.000,1900-05-06,PARACHUTE CREEK,Other,SlateGray
1057910,1057910,1057910,CO_127682,38.788897,-105.275700,1713761,8157.0-9-C-1200520,CO,1.690,0.000,0.000,1872-05-01,FOURMILE CREEK,Other,SlateGray
1057911,1057911,1057911,CO_130603,40.595127,-104.624246,1713762,20560.0-0-C-100902,CO,400.000,0.000,0.000,1906-04-17,OWL CREEK,Agricultural,SlateGray
1057912,1057912,1057912,CO_124409,37.082782,-104.792529,1713763,59017.0-0-C-1900830,CO,1.000,0.000,0.000,2011-08-01,LORENCITO CANYON,Storage,SlateGray

In [11]:
# #Exporting Outbound DataFrame to working csv file.
# outdf.to_csv('P_WaDEQA_All_MapPODSite_CRBver2.csv', index=False)  # The output

In [16]:
tempdf = pd.DataFrame()
tempdf['WBenUse'] = outdf['WBenUse'].drop_duplicates()
tempdf

              WBenUse
0               Other
4           Livestock
5            Domestic
13       Agricultural
85          Municipal
94             Mining
16383           Power
264888     Industrial
264889     Recreation
264890       Wildlife
264894     Commercial
278190  Environmental
416439        Storage
443325  Flood Control
452133           Fire
642428    Snow Making
672949       Recharge